import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar, MobileNav } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className="flex min-h-screen flex-col lg:flex-row">
          <aside className="hidden lg:block w-64 border-r min-h-screen bg-muted/10">
            <Sidebar />
          </aside>
          <div className="flex-1">
            <header className="lg:hidden border-b p-4 flex items-center">
              <MobileNav />
              <span className="font-bold ml-2">K8s Tools</span>
            </header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
