"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { CopyButton } from "@/components/tool-shell";

export function HtaccessGenerator() {
    const [options, setOptions] = useState({
        forceHttps: true,
        removeWww: true,
        preventListing: true,
        customError: false,
        gzip: true,
        cors: false,
    });

    const generate = () => {
        let conf = "# Generated by Security Suite\n\n";

        conf += "<IfModule mod_rewrite.c>\n\tRewriteEngine On\n";

        if (options.forceHttps) {
            conf += "\n\t# Force HTTPS\n";
            conf += "\tRewriteCond %{HTTPS} off\n";
            conf += "\tRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n";
        }

        if (options.removeWww) {
            conf += "\n\t# Remove WWW\n";
            conf += "\tRewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]\n";
            conf += "\tRewriteRule ^(.*)$ https://%1/$1 [R=301,L]\n";
        }

        conf += "</IfModule>\n\n";

        if (options.preventListing) {
            conf += "# Prevent Directory Listing\nOptions -Indexes\n\n";
        }

        if (options.customError) {
            conf += "# Custom Error Pages\nErrorDocument 404 /404.html\nErrorDocument 500 /500.html\n\n";
        }

        if (options.cors) {
            conf += "# Enable CORS\nHeader set Access-Control-Allow-Origin \"*\"\n\n";
        }

        return conf;
    };

    const toggle = (k: keyof typeof options) => setOptions(p => ({ ...p, [k]: !p[k] }));

    return (
        <div className="grid lg:grid-cols-2 gap-8">
            <Card>
                <CardHeader>
                    <CardTitle>Rules</CardTitle>
                    <CardDescription>Select common Apache configs.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="flex items-center space-x-2">
                        <Checkbox id="https" checked={options.forceHttps} onCheckedChange={() => toggle("forceHttps")} />
                        <label htmlFor="https" className="text-sm font-medium">Force HTTPS Redirect</label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Checkbox id="www" checked={options.removeWww} onCheckedChange={() => toggle("removeWww")} />
                        <label htmlFor="www" className="text-sm font-medium">Redirect www to non-www</label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Checkbox id="indexes" checked={options.preventListing} onCheckedChange={() => toggle("preventListing")} />
                        <label htmlFor="indexes" className="text-sm font-medium">Disable Directory Listing (-Indexes)</label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Checkbox id="cors" checked={options.cors} onCheckedChange={() => toggle("cors")} />
                        <label htmlFor="cors" className="text-sm font-medium">Enable CORS (Access-Control-Allow-Origin *)</label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Checkbox id="errors" checked={options.customError} onCheckedChange={() => toggle("customError")} />
                        <label htmlFor="errors" className="text-sm font-medium">Custom Error Pages (404, 500)</label>
                    </div>
                </CardContent>
            </Card>

            <Card className="bg-slate-900 text-slate-50 border-slate-800">
                <CardHeader>
                    <CardTitle className="text-sm uppercase tracking-wider text-slate-400">.htaccess Content</CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="relative">
                        <pre className="font-mono text-sm bg-slate-950 p-4 rounded border border-slate-800 text-green-400 min-h-[300px]">
                            {generate()}
                        </pre>
                        <div className="absolute top-4 right-4">
                            <CopyButton text={generate()} className="bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700" />
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
