// This would ideally be generated by a build script fetching from AWS
// For MVP/Phase 1, we use a static snapshot of popular instance types in us-east-1
// Prices are hourly USD.

export interface InstanceType {
    type: string;
    vCPU: number;
    memoryGB: number;
    onDemandPrice: number;
    spotPriceEst: number; // Spot varies, we use a 24h avg usage
    reserved1Yr: number; // Standard No Upfront
    architecture: "x86" | "arm";
    family: string;
}

export const INSTANCE_DATA: InstanceType[] = [
    // General Purpose (x86)
    { type: "t3.micro", vCPU: 2, memoryGB: 1, onDemandPrice: 0.0104, spotPriceEst: 0.0031, reserved1Yr: 0.006, architecture: "x86", family: "General Purpose" },
    { type: "t3.medium", vCPU: 2, memoryGB: 4, onDemandPrice: 0.0416, spotPriceEst: 0.0125, reserved1Yr: 0.025, architecture: "x86", family: "General Purpose" },
    { type: "m5.large", vCPU: 2, memoryGB: 8, onDemandPrice: 0.096, spotPriceEst: 0.035, reserved1Yr: 0.061, architecture: "x86", family: "General Purpose" },
    { type: "m5.xlarge", vCPU: 4, memoryGB: 16, onDemandPrice: 0.192, spotPriceEst: 0.070, reserved1Yr: 0.122, architecture: "x86", family: "General Purpose" },
    { type: "m5.2xlarge", vCPU: 8, memoryGB: 32, onDemandPrice: 0.384, spotPriceEst: 0.140, reserved1Yr: 0.244, architecture: "x86", family: "General Purpose" },

    // General Purpose (ARM / Graviton)
    { type: "t4g.micro", vCPU: 2, memoryGB: 1, onDemandPrice: 0.0084, spotPriceEst: 0.0025, reserved1Yr: 0.005, architecture: "arm", family: "General Purpose" },
    { type: "m6g.large", vCPU: 2, memoryGB: 8, onDemandPrice: 0.077, spotPriceEst: 0.028, reserved1Yr: 0.049, architecture: "arm", family: "General Purpose" },
    { type: "m6g.xlarge", vCPU: 4, memoryGB: 16, onDemandPrice: 0.154, spotPriceEst: 0.056, reserved1Yr: 0.098, architecture: "arm", family: "General Purpose" },

    // Compute Optimized
    { type: "c5.large", vCPU: 2, memoryGB: 4, onDemandPrice: 0.085, spotPriceEst: 0.034, reserved1Yr: 0.054, architecture: "x86", family: "Compute Optimized" },
    { type: "c5.xlarge", vCPU: 4, memoryGB: 8, onDemandPrice: 0.17, spotPriceEst: 0.068, reserved1Yr: 0.108, architecture: "x86", family: "Compute Optimized" },
    { type: "c6g.large", vCPU: 2, memoryGB: 4, onDemandPrice: 0.068, spotPriceEst: 0.022, reserved1Yr: 0.043, architecture: "arm", family: "Compute Optimized" },

    // Memory Optimized
    { type: "r5.large", vCPU: 2, memoryGB: 16, onDemandPrice: 0.126, spotPriceEst: 0.042, reserved1Yr: 0.080, architecture: "x86", family: "Memory Optimized" },
    { type: "r6g.large", vCPU: 2, memoryGB: 16, onDemandPrice: 0.1008, spotPriceEst: 0.031, reserved1Yr: 0.064, architecture: "arm", family: "Memory Optimized" },
];
