'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Copy, Clock, Database, Cloud } from 'lucide-react';
import cronParser from 'cron-parser';

export function DbBackupScheduler() {
    // DB Config
    const [dbType, setDbType] = useState<'postgres' | 'mysql'>('postgres');
    const [dbName, setDbName] = useState('production_db');
    const [dbHost, setDbHost] = useState('db.example.com');
    const [dbUser, setDbUser] = useState('backup_user');

    // Cloud Config
    const [s3Bucket, setS3Bucket] = useState('my-backup-bucket');
    const [s3Path, setS3Path] = useState('/backups/daily');
    const [region, setRegion] = useState('us-east-1');

    // Retention
    const [retentionDays, setRetentionDays] = useState('30');

    // Schedule
    const [cronExpression, setCronExpression] = useState('0 2 * * *'); // 2 AM Daily
    const [nextRuns, setNextRuns] = useState<string[]>([]);

    // Output
    const [output, setOutput] = useState('');

    useEffect(() => {
        try {
            const interval = cronParser.parseExpression(cronExpression);
            const runs = [];
            for (let i = 0; i < 5; i++) {
                runs.push(interval.next().toString());
            }
            setNextRuns(runs);
        } catch (e) {
            setNextRuns(['Invalid Cron Expression']);
        }
    }, [cronExpression]);

    useEffect(() => {
        generateScript();
    }, [dbType, dbName, dbHost, dbUser, s3Bucket, s3Path, region, retentionDays.toString()]); // Re-gen on config change

    const generateScript = () => {
        const timestamp = '$(date +%Y-%m-%d_%H-%M-%S)';
        const filename = `${dbName}_${timestamp}.sql`;
        const compressed = `${filename}.gz`;

        let script = `#!/bin/bash
# Database Backup Script generated by Database Engineering Suite
# Schedule: ${cronExpression}

# --- Configuration ---
DB_HOST="${dbHost}"
DB_USER="${dbUser}"
DB_NAME="${dbName}"
S3_BUCKET="s3://${s3Bucket}${s3Path}"
AWS_REGION="${region}"
RETENTION_DAYS=${retentionDays}
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_DIR="/tmp"

echo "[$TIMESTAMP] Starting backup for $DB_NAME..."

# 1. Dump Database
`;

        if (dbType === 'postgres') {
            script += `export PGPASSWORD="YOUR_PASSWORD_HERE" # Use .pgpass in production preferably
FILENAME="${dbName}_$TIMESTAMP.sql"
pg_dump -h $DB_HOST -U $DB_USER $DB_NAME > "$BACKUP_DIR/$FILENAME"
`;
        } else {
            script += `export MYSQL_PWD="YOUR_PASSWORD_HERE"
FILENAME="${dbName}_$TIMESTAMP.sql"
mysqldump -h $DB_HOST -u $DB_USER $DB_NAME > "$BACKUP_DIR/$FILENAME"
`;
        }

        script += `
# 2. Compress
echo "Compressing..."
gzip "$BACKUP_DIR/$FILENAME"
COMPRESSED_FILE="$FILENAME.gz"

# 3. Upload to S3
echo "Uploading to $S3_BUCKET..."
aws s3 cp "$BACKUP_DIR/$COMPRESSED_FILE" "$S3_BUCKET/$COMPRESSED_FILE" --region $AWS_REGION

# 4. Cleanup Local
rm "$BACKUP_DIR/$COMPRESSED_FILE"

# 5. Cleanup S3 (Retention)
echo "Cleaning up backups older than $RETENTION_DAYS days..."
# Note: Allows s3 lifecycle policies are better, but here is a script approach:
# (Requires aws-cli v2 and complex parsing, simplified below)
# aws s3 ls "$S3_BUCKET/" | while read -r line; do
#   params=($line)
#   createDate=\${params[0]}
#   fileName=\${params[3]}
#   ...
# done
echo "(Recommendation: Use AWS S3 Lifecycle Policies for retention instead of script logic)"

echo "[$TIMESTAMP] Backup completed successfully."
`;

        setOutput(script);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(output);
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-4 space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-base font-medium flex items-center gap-2">
                            <Database className="h-5 w-5 text-blue-500" /> Source Database
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="space-y-2">
                            <Label>Database Engine</Label>
                            <Tabs value={dbType} onValueChange={(v) => setDbType(v as any)} className="w-full">
                                <TabsList className="grid w-full grid-cols-2">
                                    <TabsTrigger value="postgres">Postgres</TabsTrigger>
                                    <TabsTrigger value="mysql">MySQL</TabsTrigger>
                                </TabsList>
                            </Tabs>
                        </div>
                        <div className="space-y-2">
                            <Label>Hostname</Label>
                            <Input value={dbHost} onChange={(e) => setDbHost(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                            <Label>Database Name</Label>
                            <Input value={dbName} onChange={(e) => setDbName(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                            <Label>Username</Label>
                            <Input value={dbUser} onChange={(e) => setDbUser(e.target.value)} />
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-base font-medium flex items-center gap-2">
                            <Cloud className="h-5 w-5 text-orange-500" /> S3 Destination
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="space-y-2">
                            <Label>Bucket Name</Label>
                            <Input value={s3Bucket} onChange={(e) => setS3Bucket(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                            <Label>Path Prefix</Label>
                            <Input value={s3Path} onChange={(e) => setS3Path(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                            <Label>AWS Region</Label>
                            <Input value={region} onChange={(e) => setRegion(e.target.value)} />
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-base font-medium flex items-center gap-2">
                            <Clock className="h-5 w-5 text-purple-500" /> Frequency
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="space-y-2">
                            <Label>Cron Schedule</Label>
                            <Input value={cronExpression} onChange={(e) => setCronExpression(e.target.value)} fontMono />
                            <div className="text-xs text-slate-500 bg-slate-50 dark:bg-slate-900 p-2 rounded">
                                <strong>Next Runs:</strong>
                                <ul className="pl-4 list-disc mt-1 space-y-0.5">
                                    {nextRuns.map((run, i) => <li key={i}>{run}</li>)}
                                </ul>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="lg:col-span-8 space-y-6">
                <Card className="h-[800px] flex flex-col border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
                    <CardHeader className="pb-3 border-b flex flex-row items-center justify-between space-y-0 bg-slate-50/50 dark:bg-slate-900/50">
                        <CardTitle className="flex items-center gap-2 text-base font-medium">
                            Generated Bash Script
                        </CardTitle>
                        <Button variant="secondary" size="sm" onClick={copyToClipboard} className="h-7 text-xs gap-2">
                            <Copy className="h-3 w-3" /> Copy Script
                        </Button>
                    </CardHeader>
                    <CardContent className="flex-1 p-0">
                        <pre className="w-full h-full p-4 overflow-auto font-mono text-sm text-slate-700 dark:text-slate-300 bg-white dark:bg-slate-950">
                            {output}
                        </pre>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
