'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Trash2, Plus, Copy, AlertTriangle, ShieldCheck } from 'lucide-react';

type HbaRecord = {
    id: string;
    type: 'local' | 'host' | 'hostssl' | 'hostnossl';
    database: string;
    user: string;
    address?: string; // Only for host* types
    method: 'trust' | 'reject' | 'md5' | 'password' | 'scram-sha-256' | 'peer' | 'cert';
};

const DEFAULT_RECORDS: HbaRecord[] = [
    { id: '1', type: 'local', database: 'all', user: 'postgres', method: 'peer' },
    { id: '2', type: 'local', database: 'all', user: 'all', method: 'peer' },
    { id: '3', type: 'host', database: 'all', user: 'all', address: '127.0.0.1/32', method: 'scram-sha-256' },
    { id: '4', type: 'host', database: 'all', user: 'all', address: '::1/128', method: 'scram-sha-256' },
];

export function PgHbaGenerator() {
    const [records, setRecords] = useState<HbaRecord[]>(DEFAULT_RECORDS);
    const [output, setOutput] = useState('');
    const [warnings, setWarnings] = useState<string[]>([]);

    useEffect(() => {
        generateConfig();
    }, [records]);

    const addRecord = () => {
        setRecords([...records, {
            id: Date.now().toString(),
            type: 'host',
            database: 'all',
            user: 'all',
            address: '0.0.0.0/0',
            method: 'scram-sha-256'
        }]);
    };

    const removeRecord = (id: string) => {
        setRecords(records.filter(r => r.id !== id));
    };

    const updateRecord = (id: string, field: keyof HbaRecord, value: string) => {
        setRecords(records.map(r => r.id === id ? { ...r, [field]: value } : r));
    };

    const generateConfig = () => {
        let text = '# PostgreSQL Client Authentication Configuration File\n';
        text += '# Generated by Database Engineering Suite\n#\n';
        text += '# TYPE  DATABASE        USER            ADDRESS                 METHOD\n\n';

        const newWarnings: string[] = [];

        records.forEach(r => {
            let line = '';

            // Pad columns for readability (TAB separated generally preferred but spaces work generally)
            // Postgres parses spaces/tabs. We'll use fixed width alignment logic.
            const typeStr = r.type.padEnd(8);
            const dbStr = r.database.padEnd(16);
            const userStr = r.user.padEnd(16);

            let addrStr = '';
            if (r.type.startsWith('host')) {
                addrStr = (r.address || '').padEnd(24);

                // Security Check: host all all 0.0.0.0/0 trust
                if (r.address === '0.0.0.0/0' && r.method === 'trust') {
                    newWarnings.push(`Line with TYPE=${r.type} ADDRESS=0.0.0.0/0 uses method 'trust'. This is extremely dangerous.`);
                }
                // Security Check: password method is weak
                if (r.method === 'password') {
                    newWarnings.push(`Method 'password' sends cleartext passwords. Prefer 'scram-sha-256' or 'md5'.`);
                }
            } else {
                addrStr = ''.padEnd(24); // Local sockets have no address
            }

            const methodStr = r.method;
            line = `${typeStr}${dbStr}${userStr}${addrStr}${methodStr}`;
            text += line + '\n';
        });

        setOutput(text);
        setWarnings(newWarnings);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(output);
    };

    return (
        <div className="space-y-6">
            <Card className="border-slate-200 dark:border-slate-800 shadow-sm">
                <CardHeader className="flex flex-row items-center justify-between">
                    <div>
                        <CardTitle className="text-lg">Access Rules</CardTitle>
                        <CardDescription>Configure who can connect to your Postgres server.</CardDescription>
                    </div>
                    <Button onClick={addRecord} size="sm" className="gap-2">
                        <Plus className="h-4 w-4" /> Add Rule
                    </Button>
                </CardHeader>
                <CardContent className="p-0">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead className="w-[120px]">Type</TableHead>
                                    <TableHead>Database</TableHead>
                                    <TableHead>User</TableHead>
                                    <TableHead className="w-[180px]">Address (CIDR)</TableHead>
                                    <TableHead className="w-[150px]">Method</TableHead>
                                    <TableHead className="w-[50px]"></TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {records.map((r) => (
                                    <TableRow key={r.id}>
                                        <TableCell>
                                            <Select value={r.type} onValueChange={(v) => updateRecord(r.id, 'type', v)}>
                                                <SelectTrigger className="h-8 w-full border-0 shadow-none bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800">
                                                    <SelectValue />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectItem value="local">local (Unix)</SelectItem>
                                                    <SelectItem value="host">host (TCP/IP)</SelectItem>
                                                    <SelectItem value="hostssl">hostssl</SelectItem>
                                                    <SelectItem value="hostnossl">hostnossl</SelectItem>
                                                </SelectContent>
                                            </Select>
                                        </TableCell>
                                        <TableCell>
                                            <Input
                                                value={r.database}
                                                onChange={(e) => updateRecord(r.id, 'database', e.target.value)}
                                                className="h-8 border-0 shadow-none bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800 focus-visible:ring-0"
                                            />
                                        </TableCell>
                                        <TableCell>
                                            <Input
                                                value={r.user}
                                                onChange={(e) => updateRecord(r.id, 'user', e.target.value)}
                                                className="h-8 border-0 shadow-none bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800 focus-visible:ring-0"
                                            />
                                        </TableCell>
                                        <TableCell>
                                            {r.type.startsWith('host') ? (
                                                <Input
                                                    value={r.address}
                                                    onChange={(e) => updateRecord(r.id, 'address', e.target.value)}
                                                    className="h-8 border-0 shadow-none bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800 focus-visible:ring-0 font-mono text-xs"
                                                    placeholder="0.0.0.0/0"
                                                />
                                            ) : (
                                                <span className="text-xs text-slate-400 pl-3">N/A</span>
                                            )}
                                        </TableCell>
                                        <TableCell>
                                            <Select value={r.method} onValueChange={(v) => updateRecord(r.id, 'method', v)}>
                                                <SelectTrigger className={`h-8 w-full border-0 shadow-none bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800 ${r.method === 'trust' ? 'text-red-500 font-bold' : ''}`}>
                                                    <SelectValue />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectItem value="scram-sha-256">scram-sha-256</SelectItem>
                                                    <SelectItem value="md5">md5</SelectItem>
                                                    <SelectItem value="password">password</SelectItem>
                                                    <SelectItem value="trust" className="text-red-500">trust (DANGER)</SelectItem>
                                                    <SelectItem value="reject">reject</SelectItem>
                                                    <SelectItem value="peer">peer</SelectItem>
                                                    <SelectItem value="cert">cert</SelectItem>
                                                </SelectContent>
                                            </Select>
                                        </TableCell>
                                        <TableCell>
                                            <Button variant="ghost" size="sm" onClick={() => removeRecord(r.id)} className="h-8 w-8 p-0 text-slate-400 hover:text-red-500">
                                                <Trash2 className="h-4 w-4" />
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </CardContent>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Output */}
                <Card className="lg:col-span-2 border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
                    <CardHeader className="pb-3 border-b flex flex-row items-center justify-between space-y-0 bg-slate-50/50 dark:bg-slate-900/50">
                        <CardTitle className="flex items-center gap-2 text-base font-medium">
                            <ShieldCheck className="h-4 w-4 text-green-500" /> Generated Configuration
                        </CardTitle>
                        <Button variant="secondary" size="sm" onClick={copyToClipboard} className="h-7 text-xs gap-2">
                            <Copy className="h-3 w-3" /> Copy Output
                        </Button>
                    </CardHeader>
                    <CardContent className="p-0">
                        <pre className="w-full p-4 overflow-auto font-mono text-sm text-slate-700 dark:text-slate-300 bg-white dark:bg-slate-950 leading-6">
                            {output}
                        </pre>
                    </CardContent>
                </Card>

                {/* Warnings */}
                <Card className="border-red-100 dark:border-red-900/20 bg-red-50/50 dark:bg-red-900/5 shadow-sm">
                    <CardHeader className="pb-2">
                        <CardTitle className="flex items-center gap-2 text-base font-medium text-red-600 dark:text-red-400">
                            <AlertTriangle className="h-4 w-4" /> Security Checks
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        {warnings.length === 0 ? (
                            <div className="flex flex-col items-center justify-center h-32 text-green-600 dark:text-green-500 gap-2">
                                <ShieldCheck className="h-8 w-8" />
                                <span className="text-sm font-medium">No configuration issues detected.</span>
                            </div>
                        ) : (
                            <ul className="space-y-3">
                                {warnings.map((w, i) => (
                                    <li key={i} className="text-xs text-red-600 dark:text-red-300 bg-red-100 dark:bg-red-900/30 p-2 rounded-md border border-red-200 dark:border-red-900/50">
                                        {w}
                                    </li>
                                ))}
                            </ul>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
